# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'gesture' do
        pod 'PebbleKit'
	pod 'CorePlot'
	pod 'Firebase', '>= 2.3.3'
end

target 'gestureTests' do

end
